# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculate.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(529, 507)
        Form.setMinimumSize(QtCore.QSize(529, 507))
        Form.setMaximumSize(QtCore.QSize(529, 507))
        self.pushButton_div = QtWidgets.QPushButton(Form)
        self.pushButton_div.setGeometry(QtCore.QRect(400, 350, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_plus = QtWidgets.QPushButton(Form)
        self.pushButton_plus.setGeometry(QtCore.QRect(400, 420, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 140, 361, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(30, 10, 461, 71))
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.disp_stack = QtWidgets.QLabel(Form)
        self.disp_stack.setGeometry(QtCore.QRect(30, 90, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.disp_stack.setFont(font)
        self.disp_stack.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.disp_stack.setFrameShape(QtWidgets.QFrame.Box)
        self.disp_stack.setFrameShadow(QtWidgets.QFrame.Raised)
        self.disp_stack.setLineWidth(1)
        self.disp_stack.setMidLineWidth(0)
        self.disp_stack.setText("")
        self.disp_stack.setScaledContents(False)
        self.disp_stack.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.disp_stack.setObjectName("disp_stack")
        self.pushButton_step = QtWidgets.QPushButton(Form)
        self.pushButton_step.setGeometry(QtCore.QRect(400, 140, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_step.setFont(font)
        self.pushButton_step.setObjectName("pushButton_step")
        self.pushButton_del = QtWidgets.QPushButton(Form)
        self.pushButton_del.setGeometry(QtCore.QRect(400, 280, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_del.setFont(font)
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_mul = QtWidgets.QPushButton(Form)
        self.pushButton_mul.setGeometry(QtCore.QRect(400, 210, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setObjectName("pushButton_mul")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.pushButton_div.setText(_translate("Form", "-"))
        self.pushButton_plus.setText(_translate("Form", "+"))
        self.pushButton_step.setText(_translate("Form", "^"))
        self.pushButton_del.setText(_translate("Form", "/"))
        self.pushButton_mul.setText(_translate("Form", "*"))

