# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_weather.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TableWeather(object):
    def setupUi(self, TableWeather):
        TableWeather.setObjectName("TableWeather")
        TableWeather.resize(420, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TableWeather.sizePolicy().hasHeightForWidth())
        TableWeather.setSizePolicy(sizePolicy)
        TableWeather.setMinimumSize(QtCore.QSize(420, 130))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        TableWeather.setFont(font)
        TableWeather.setAutoFillBackground(False)
        TableWeather.setStyleSheet("background-color:white;")
        TableWeather.setFrameShape(QtWidgets.QFrame.Box)
        TableWeather.setFrameShadow(QtWidgets.QFrame.Raised)
        TableWeather.setLineWidth(2)
        self.formLayoutWidget = QtWidgets.QWidget(TableWeather)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.label_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_name.setObjectName("label_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_name)
        self.label_descr = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_descr.setObjectName("label_descr")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_descr)
        self.label_hum = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_hum.setObjectName("label_hum")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_hum)
        self.label_wing = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_wing.setObjectName("label_wing")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_wing)
        self.text_name = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.text_name.setFont(font)
        self.text_name.setText("")
        self.text_name.setObjectName("text_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.text_name)
        self.text_descr = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.text_descr.setFont(font)
        self.text_descr.setText("")
        self.text_descr.setObjectName("text_descr")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.text_descr)
        self.text_hum = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.text_hum.setFont(font)
        self.text_hum.setText("")
        self.text_hum.setObjectName("text_hum")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.text_hum)
        self.text_wing = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.text_wing.setFont(font)
        self.text_wing.setText("")
        self.text_wing.setObjectName("text_wing")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.text_wing)
        self.label_temp = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_temp.setObjectName("label_temp")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_temp)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_2)

        self.retranslateUi(TableWeather)
        QtCore.QMetaObject.connectSlotsByName(TableWeather)

    def retranslateUi(self, TableWeather):
        _translate = QtCore.QCoreApplication.translate
        TableWeather.setWindowTitle(_translate("TableWeather", "Frame"))
        self.label_name.setText(_translate("TableWeather", "Время"))
        self.label_descr.setText(_translate("TableWeather", "Описание"))
        self.label_hum.setText(_translate("TableWeather", "Влажность, %"))
        self.label_wing.setText(_translate("TableWeather", "Ветер, м/c"))
        self.label_temp.setText(_translate("TableWeather", "Температра, C"))

