# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WeatherWidget(object):
    def setupUi(self, WeatherWidget):
        WeatherWidget.setObjectName("WeatherWidget")
        WeatherWidget.resize(640, 725)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WeatherWidget.sizePolicy().hasHeightForWidth())
        WeatherWidget.setSizePolicy(sizePolicy)
        WeatherWidget.setMinimumSize(QtCore.QSize(640, 725))
        WeatherWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_submit = QtWidgets.QPushButton(WeatherWidget)
        self.button_submit.setGeometry(QtCore.QRect(460, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.button_submit.setFont(font)
        self.button_submit.setObjectName("button_submit")
        self.label_not_foud = QtWidgets.QLabel(WeatherWidget)
        self.label_not_foud.setEnabled(True)
        self.label_not_foud.setGeometry(QtCore.QRect(90, 90, 451, 131))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(18)
        self.label_not_foud.setFont(font)
        self.label_not_foud.setAlignment(QtCore.Qt.AlignCenter)
        self.label_not_foud.setObjectName("label_not_foud")
        self.verticalLayoutWidget = QtWidgets.QWidget(WeatherWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 120, 581, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_current = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_current.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_current.setContentsMargins(0, 0, 0, 0)
        self.layout_current.setObjectName("layout_current")
        self.text_weather = QtWidgets.QLineEdit(WeatherWidget)
        self.text_weather.setGeometry(QtCore.QRect(10, 10, 441, 41))
        self.text_weather.setMaxLength(100)
        self.text_weather.setObjectName("text_weather")
        self.label_cur = QtWidgets.QLabel(WeatherWidget)
        self.label_cur.setGeometry(QtCore.QRect(20, 90, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.label_cur.setFont(font)
        self.label_cur.setObjectName("label_cur")
        self.label_for = QtWidgets.QLabel(WeatherWidget)
        self.label_for.setGeometry(QtCore.QRect(20, 250, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.label_for.setFont(font)
        self.label_for.setObjectName("label_for")
        self.scrollArea = QtWidgets.QScrollArea(WeatherWidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 280, 611, 431))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 611, 431))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 581, 431))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_place = QtWidgets.QLabel(WeatherWidget)
        self.label_place.setGeometry(QtCore.QRect(20, 60, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.label_place.setFont(font)
        self.label_place.setObjectName("label_place")
        self.lineEdit_place = QtWidgets.QLineEdit(WeatherWidget)
        self.lineEdit_place.setGeometry(QtCore.QRect(110, 60, 491, 21))
        self.lineEdit_place.setMaxLength(100)
        self.lineEdit_place.setReadOnly(True)
        self.lineEdit_place.setObjectName("lineEdit_place")
        self.line = QtWidgets.QFrame(WeatherWidget)
        self.line.setGeometry(QtCore.QRect(20, 270, 581, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(WeatherWidget)
        QtCore.QMetaObject.connectSlotsByName(WeatherWidget)

    def retranslateUi(self, WeatherWidget):
        _translate = QtCore.QCoreApplication.translate
        WeatherWidget.setWindowTitle(_translate("WeatherWidget", "Weather"))
        self.button_submit.setText(_translate("WeatherWidget", "Показать погоду"))
        self.label_not_foud.setText(_translate("WeatherWidget", "ПОГОДА НЕ НАЙДЕНА"))
        self.text_weather.setPlaceholderText(_translate("WeatherWidget", "Введите текст"))
        self.label_cur.setText(_translate("WeatherWidget", "Погода сейчас"))
        self.label_for.setText(_translate("WeatherWidget", "Прогноз погоды"))
        self.label_place.setText(_translate("WeatherWidget", "Погода для"))

